### ISSUE TITLE
Does not parse `const`

### ISSUE THREAD

**Issue by jacwright** [capaj/require-globify#25]
The keyword `const` is now available in many browsers and in node.js. Browserify/watchify parse `const` just fine, but when adding `require-globify` to the transforms the error

> SyntaxError: Unexpected token...

is thrown for those const keywords.

**Comment by capaj** [comment]
Just throwing in a callstack:
SyntaxError: Unexpected token (1:6) (while require-globify was processing /home/capaj/git_projects/es6-6to5-browserify-boilerplate/src2/a.js) while parsing file: /home/capaj/git_projects/es6-6to5-browserify-boilerplate/src2/a.js
    at Parser.pp.raise (/home/capaj/git_projects/es6-6to5-browserify-boilerplate/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.unexpected (/home/capaj/git_projects/es6-6to5-browserify-boilerplate/node_modules/acorn/dist/acorn.js:2264:8)
    at Parser.pp.semicolon (/home/capaj/git_projects/es6-6to5-browserify-boilerplate/node_modules/acorn/dist/acorn.js:2243:59)
    at Parser.pp.parseExpressionStatement (/home/capaj/git_projects/es6-6to5-browserify-boilerplate/node_modules/acorn/dist/acorn.js:2677:8)
    at Parser.pp.parseStatement (/home/capaj/git_projects/es6-6to5-browserify-boilerplate/node_modules/acorn/dist/acorn.js:2462:160)
    at Parser.pp.parseTopLevel (/home/capaj/git_projects/es6-6to5-browserify-boilerplate/node_modules/acorn/dist/acorn.js:2379:21)
    at parse (/home/capaj/git_projects/es6-6to5-browserify-boilerplate/node_modules/acorn/dist/acorn.js:101:12)
    at module.exports (/home/capaj/git_projects/es6-6to5-browserify-boilerplate/node_modules/falafel/index.js:22:15)
    at Stream.<anonymous> (/home/capaj/git_projects/es6-6to5-browserify-boilerplate/node_modules/browserify-transform-tools/lib/transformTools.js:187:21)
    at Stream.end (/home/capaj/git_projects/es6-6to5-browserify-boilerplate/node_modules/browserify-transform-tools/lib/transformTools.js:108:30)

**Comment by capaj** [comment]
@jacwright should be fixed, I will let @call-a3 couple of days to merge it, if he's not available, will bump and release it as 1.4.0 myself
